--DROP TABLE NHANVIEN ;
--DROP TABLE PHONGBAN;
--DROP TABLE DEAN;
--DROP TABLE PHANCONG;

CREATE TABLE NHANVIEN
(
    MANV VARCHAR2(10) PRIMARY KEY,
    TENNV VARCHAR (50),
    PHAI VARCHAR2 (10),
    NGAYSINH DATE,
    DIACHI VARCHAR2 (10),
    SODT VARCHAR2(10),
    LUONG INT,
    PHUCAP INT,
    VAITRO VARCHAR2(50),
    MANQL VARCHAR2 (10),
    PHG VARCHAR2 (10)
);
CREATE TABLE PHONGBAN
(
    MAPB VARCHAR2(10) PRIMARY KEY,
    TENPB VARCHAR2(50),
    TRPHG VARCHAR2(10)
);
create table DEAN (
    MADA varchar2(10)PRIMARY KEY,
    TENDA varchar2(10),
    NGAYBD date,
    PHONG varchar2(10)
);
CREATE TABLE PHANCONG
(
    MANV VARCHAR2(10) ,
    MADA VARCHAR2(10) ,
    THOIGIAN DATE ,
    PRIMARY KEY (MANV,MADA)
);

ALTER TABLE PHONGBAN
ADD CONSTRAINT FK_PHONGBAN_NHANVIEN
FOREIGN KEY (TRPHG)
REFERENCES NHANVIEN(MANV);

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_NHANVIEN
FOREIGN KEY (MANQL)
REFERENCES NHANVIEN (MANV);

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_PHONGBAN
FOREIGN KEY (PHG)
REFERENCES PHONGBAN(MAPB);

ALTER TABLE DEAN
ADD CONSTRAINT FK_DEAN_PHONGBAN
FOREIGN KEY (PHONG)
REFERENCES PHONGBAN(MAPB);

--
-- KHOA NGOAI CUA PHANCONG
ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_NHANVIEN
FOREIGN KEY(MANV)
REFERENCES NHANVIEN(MANV);

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_DEAN
FOREIGN KEY(MADA)
REFERENCES DEAN(MADA);
