DROP USER AD_N5 CASCADE;
alter session set "_ORACLE_SCRIPT"=true; 
CREATE USER AD_N5 IDENTIFIED BY 123;

GRANT ALL PRIVILEGES TO AD_N5 with ADMIN OPTION;

GRANT SELECT ON DBA_TAB_PRIVS TO AD_N5 WITH GRANT OPTION;
GRANT SELECT ON ROLE_TAB_PRIVS TO AD_N5 WITH GRANT OPTION;

GRANT SELECT ON dba_tables to AD_N5 WITH GRANT OPTION;

GRANT SELECT ON dba_users to AD_N5 WITH GRANT OPTION;

GRANT SELECT ON USER_ROLE_PRIVS to AD_N5 WITH GRANT OPTION;
GRANT SELECT ON DBA_ROLES to AD_N5 WITH GRANT OPTION;

GRANT EXECUTE ON DBMS_RLS TO AD_N5;
GRANT EXECUTE ON DBMS_CRYPTO TO AD_N5;


GRANT UNLIMITED TABLESPACE TO AD_N5;

GRANT EXECUTE ON DBMS_FGA TO AD_N5;
GRANT SELECT ON UNIFIED_AUDIT_TRAIL TO AD_N5;
GRANT SELECT ON dba_audit_trail TO AD_N5;
